spring:
  application:
    name: dualeasy-auth
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_test
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080
